# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/microblazeblock_axi_smc_0.xci
# IP: The module: 'microblazeblock_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/bd_6bd4.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_12/bd_6bd4_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_21/bd_6bd4_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_24/bd_6bd4_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_30/bd_6bd4_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_25/bd_6bd4_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_26/bd_6bd4_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_27/bd_6bd4_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_28/bd_6bd4_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_29/bd_6bd4_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_22/bd_6bd4_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_23/bd_6bd4_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_18/bd_6bd4_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_19/bd_6bd4_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_20/bd_6bd4_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_13/bd_6bd4_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_14/bd_6bd4_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_15/bd_6bd4_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_16/bd_6bd4_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_17/bd_6bd4_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_9/bd_6bd4_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_10/bd_6bd4_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_11/bd_6bd4_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_4/bd_6bd4_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_5/bd_6bd4_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_6/bd_6bd4_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_7/bd_6bd4_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_8/bd_6bd4_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_0/bd_6bd4_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_1/bd_6bd4_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_2/bd_6bd4_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_3/bd_6bd4_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_12/bd_6bd4_s00a2s_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_21/bd_6bd4_s01a2s_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_24/bd_6bd4_m00s2a_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_25/bd_6bd4_m00arn_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_26/bd_6bd4_m00rn_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_27/bd_6bd4_m00awn_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_28/bd_6bd4_m00wn_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_29/bd_6bd4_m00bn_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_22/bd_6bd4_sarn_1_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_23/bd_6bd4_srn_1_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_13/bd_6bd4_sarn_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_14/bd_6bd4_srn_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_15/bd_6bd4_sawn_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_16/bd_6bd4_swn_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_17/bd_6bd4_sbn_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_4/bd_6bd4_arsw_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_5/bd_6bd4_rsw_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_6/bd_6bd4_awsw_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_7/bd_6bd4_wsw_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_8/bd_6bd4_bsw_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_1/bd_6bd4_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_1/bd_6bd4_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_2/bd_6bd4_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_2/bd_6bd4_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_3/bd_6bd4_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_3/bd_6bd4_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblazeblock_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/microblazeblock_axi_smc_0.xci
# IP: The module: 'microblazeblock_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/bd_6bd4.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_12/bd_6bd4_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_21/bd_6bd4_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_24/bd_6bd4_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_30/bd_6bd4_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_25/bd_6bd4_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_26/bd_6bd4_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_27/bd_6bd4_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_28/bd_6bd4_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_29/bd_6bd4_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_22/bd_6bd4_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_23/bd_6bd4_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_18/bd_6bd4_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_19/bd_6bd4_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_20/bd_6bd4_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_13/bd_6bd4_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_14/bd_6bd4_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_15/bd_6bd4_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_16/bd_6bd4_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_17/bd_6bd4_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_9/bd_6bd4_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_10/bd_6bd4_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_11/bd_6bd4_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_4/bd_6bd4_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_5/bd_6bd4_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_6/bd_6bd4_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_7/bd_6bd4_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_8/bd_6bd4_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_0/bd_6bd4_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_1/bd_6bd4_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_2/bd_6bd4_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_3/bd_6bd4_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_12/bd_6bd4_s00a2s_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_21/bd_6bd4_s01a2s_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_24/bd_6bd4_m00s2a_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_25/bd_6bd4_m00arn_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_26/bd_6bd4_m00rn_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_27/bd_6bd4_m00awn_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_28/bd_6bd4_m00wn_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_29/bd_6bd4_m00bn_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_22/bd_6bd4_sarn_1_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_23/bd_6bd4_srn_1_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_13/bd_6bd4_sarn_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_14/bd_6bd4_srn_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_15/bd_6bd4_sawn_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_16/bd_6bd4_swn_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_17/bd_6bd4_sbn_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_4/bd_6bd4_arsw_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_5/bd_6bd4_rsw_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_6/bd_6bd4_awsw_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_7/bd_6bd4_wsw_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_8/bd_6bd4_bsw_0_ooc.xdc

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_1/bd_6bd4_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_1/bd_6bd4_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_2/bd_6bd4_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_2/bd_6bd4_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_3/bd_6bd4_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/bd_0/ip/ip_3/bd_6bd4_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblazeblock_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
