# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/microblazeblock/microblazeblock.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazeblock || ORIG_REF_NAME==microblazeblock} -quiet] -quiet

# IP: bd/microblazeblock/ip/microblazeblock_microblaze_0_0/microblazeblock_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazeblock_microblaze_0_0 || ORIG_REF_NAME==microblazeblock_microblaze_0_0} -quiet] -quiet

# IP: bd/microblazeblock/ip/microblazeblock_mdm_1_0/microblazeblock_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazeblock_mdm_1_0 || ORIG_REF_NAME==microblazeblock_mdm_1_0} -quiet] -quiet

# IP: bd/microblazeblock/ip/microblazeblock_clk_wiz_1_0/microblazeblock_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazeblock_clk_wiz_1_0 || ORIG_REF_NAME==microblazeblock_clk_wiz_1_0} -quiet] -quiet

# IP: bd/microblazeblock/ip/microblazeblock_rst_clk_wiz_1_100M_0/microblazeblock_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazeblock_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==microblazeblock_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/microblazeblock/ip/microblazeblock_axi_uartlite_0_0/microblazeblock_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazeblock_axi_uartlite_0_0 || ORIG_REF_NAME==microblazeblock_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/microblazeblock/ip/microblazeblock_microblaze_0_axi_periph_0/microblazeblock_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazeblock_microblaze_0_axi_periph_0 || ORIG_REF_NAME==microblazeblock_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/microblazeblock/ip/microblazeblock_mig_7series_0_1/microblazeblock_mig_7series_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazeblock_mig_7series_0_1 || ORIG_REF_NAME==microblazeblock_mig_7series_0_1} -quiet] -quiet

# IP: bd/microblazeblock/ip/microblazeblock_axi_smc_0/microblazeblock_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazeblock_axi_smc_0 || ORIG_REF_NAME==microblazeblock_axi_smc_0} -quiet] -quiet

# IP: bd/microblazeblock/ip/microblazeblock_rst_mig_7series_0_81M_0/microblazeblock_rst_mig_7series_0_81M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazeblock_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==microblazeblock_rst_mig_7series_0_81M_0} -quiet] -quiet

# IP: bd/microblazeblock/ip/microblazeblock_dlmb_v10_0/microblazeblock_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazeblock_dlmb_v10_0 || ORIG_REF_NAME==microblazeblock_dlmb_v10_0} -quiet] -quiet

# IP: bd/microblazeblock/ip/microblazeblock_ilmb_v10_0/microblazeblock_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazeblock_ilmb_v10_0 || ORIG_REF_NAME==microblazeblock_ilmb_v10_0} -quiet] -quiet

# IP: bd/microblazeblock/ip/microblazeblock_dlmb_bram_if_cntlr_0/microblazeblock_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazeblock_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==microblazeblock_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/microblazeblock/ip/microblazeblock_ilmb_bram_if_cntlr_0/microblazeblock_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazeblock_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==microblazeblock_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/microblazeblock/ip/microblazeblock_lmb_bram_0/microblazeblock_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblazeblock_lmb_bram_0 || ORIG_REF_NAME==microblazeblock_lmb_bram_0} -quiet] -quiet

# XDC: bd/microblazeblock/microblazeblock_ooc.xdc
