# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_ilmb_v10_0/microblazeblock_ilmb_v10_0.xci
# IP: The module: 'microblazeblock_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_ilmb_v10_0/microblazeblock_ilmb_v10_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblazeblock_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_ilmb_v10_0/microblazeblock_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblazeblock_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_ilmb_v10_0/microblazeblock_ilmb_v10_0.xci
# IP: The module: 'microblazeblock_ilmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_ilmb_v10_0/microblazeblock_ilmb_v10_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblazeblock_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Administrator/Documents/project_10blaze/project_10blaze.srcs/sources_1/bd/microblazeblock/ip/microblazeblock_ilmb_v10_0/microblazeblock_ilmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblazeblock_ilmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
